export interface Props {
  accept?: string;
  activities?: string;
  auth?:boolean;
  days?: Array | string;
  detailDays?: string;
  areas?: Array | string;
  average?: string;
  buttonTitle?: string;
  buttonIcon?: string;
  buttonType?: string;
  buttonValue?: string;
  body?: string;
  caution?:string;
  classes?: string;
  color?: string;
  confirm?: boolean;
  detailActivities?: string;
  detailAreas?: string;
  disabled?: boolean;
  fromAge?: string;
  headerImgPath?: string;
  thumbnailPath?: string;
  height?: number | string;
  icon?: string;
  id?: string | number;
  introduction?: string;
  isSelecting?: boolean;
  items?: Array | string;
  label?: string;
  member?: string | number;
  memberCount?: number;
  name?: string | undefined;
  padding?: string;
  page?: string;
  path?: string;
  pathHeader?: string;
  pathThumbnail?: string;
  persistent?:boolean;
  placeholder?: string;
  prependIcon?: string;
  profiles?: Array | string;
  provider?: string;
  rides?: Array | string;
  size?: number | string;
  subTitle?: string;
  teamName?: string;
  teamUrl?: string;
  text?: string;
  title?: string;
  to?: string;
  toAge?: string;
  toggle?: boolean;
  type?: string;
  userId?: number | string;
  val?: string | number | boolean;
  variant?: string;
}
