export interface Props {
  accept?: string;
  activities: string;
  auth?:boolean;
  days: string;
  detailDays: string;
  areas: string[];
  average: string;
  buttonTitle?: string;
  buttonIcon?: string;
  body: string;
  classes: string;
  color?: string | null;
  confirm: boolean;
  detailActivities: string;
  detailAreas: string;
  disabled?: boolean;
  fromAge: string;
  headerImgPath?: string;
  thumbnailPath?: string;
  height?: number;
  icon: string;
  id: string;
  introduction: string;
  isSelecting: boolean;
  items: string[];
  label: string;
  member: string;
  memberCount: number;
  name?: string | undefined | null;
  padding?: string;
  page?: string | null;
  path: string;
  pathHeader: string;
  pathThumbnail: string;
  placeholder?: string;
  prependIcon?: string;
  profiles: string;
  provider: string;
  rides: string[];
  size?: number;
  subTitle: string;
  teamName: string;
  teamUrl: string;
  text: string;
  title: string;
  to?: string | null;
  toAge: string;
  toggle: boolean;
  type?: string;
  userId: number;
  val?: boolean | string | number | null;
  variant: string;
  // variant: NonNullable<"elevated" | "flat" | "text" | "tonal" | "outlined" | "plain"> | undefined;
}
