
export const Message = {
  LOGIN:'ログインしました',
  LOGOUT:'ログアウトしました',
  REGISTER:'登録しました',
  DELETE:'削除しました',
  UPDATE:'更新しました',
  REGISTERERROR:'登録できませんでした。<br>再度お試しください。',
  DELETEERROR:'削除できませんでした。再度お試しください。',
  UPDATEERROR:'更新できませんでした。再度お試しください。',
  LOGINERROR:'メールアドレスもしくはパスワードが一致しません',
  REGISTERNAMEERROR:'ユーザーネームは既に使用されています',
  REGISTEREMAILERROR:'登録に失敗しました。入力情報を再度ご確認ください',
  SENDMESSAGE:'メッセージを送信しました',
  SENDMESSAGEERROR:'メッセージを送信しました',
  RESETPASSWORD:'パスワードをリセットしました',
  RESETPASSWORDERROR:'パスワードのリセットに失敗しました。再度お試しください',
  WITHDRAW:'退会しました',
  WITHDRAWERROR:'エラーが発生しました。再度お試しください。',
}
