import {
  mdiAccount,
  mdiHome,
  mdiAccountCircle,
  mdiBike,
  mdiInformation,
  mdiMapMarker,
  mdiBicycle,
  mdiNoteEdit,
  mdiLoginVariant,
  mdiLogoutVariant,
  mdiMagnify,
  mdiNavigation,
  mdiCalendarMonth,
  mdiCloseCircleOutline,
  mdiViewDashboard,
  mdiMessageProcessing,
  mdiChevronLeft,
  mdiCloudUpload,
  mdiAccountSearch,
  mdiCog,
  mdiListBox,
  mdiAccountGroup,
  mdiSelectGroup
} from "@mdi/js";


export const Icons = {
  ACCOUNT:mdiAccount,
  AFFILIATION:mdiSelectGroup,
  BACK:mdiChevronLeft,
  BICYCLE:mdiBicycle,
  CLOSE:mdiCloseCircleOutline,
  CYCLING:mdiBike,
  DASHBOARD:mdiViewDashboard,
  HOME:mdiHome,
  INFORMATION:mdiInformation,
  LOGIN:mdiLoginVariant,
  LOGOUT:mdiLogoutVariant,
  MAP:mdiMapMarker,
  MESSAGES:mdiMessageProcessing,
  MYPAGE:mdiAccountCircle,
  MYTEAM:mdiAccountGroup,
  NAVI:mdiNavigation,
  RECRUIT:mdiAccountSearch,
  REGISTER:mdiNoteEdit,
  SCHEDULE:mdiCalendarMonth,
  SEARCH:mdiMagnify,
  SETTING:mdiCog,
  TEAMS:mdiListBox,
  UPLOAD:mdiCloudUpload
}
