<template>
  <div>
    <v-row>
      <v-col>
        <v-btn
          variant="outlined"
          rounded="0"
          class="relative d-block mx-auto border-2 border-indigo-500 w-[250px]"
        >
          <v-img
            contain
            src="../../assets/images/google.png"
            class="mr-auto"
            width="20"
            height="20"
          />
          Googleで登録
        </v-btn>
      </v-col>
      <v-col>
        <v-btn
          variant="outlined"
          rounded="0"
          class="d-block mx-auto border-2 border-indigo-500 w-[250px]"
        >
          <v-img
            contain
            src="../../assets/images/twitter.png"
            class="mr-auto"
            width="20"
            height="20"
          />
          Twitterで登録
        </v-btn>
      </v-col>
    </v-row>
  </div>
</template>
